'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblInsuree
    Public Property InsureeID As Integer
    Public Property InsureeUUID As Guid
    Public Property FamilyID As Integer
    Public Property CHFID As String
    Public Property LastName As String
    Public Property OtherNames As String
    Public Property DOB As Date
    Public Property Gender As String
    Public Property Marital As String
    Public Property IsHead As Boolean
    Public Property passport As String
    Public Property Phone As String
    Public Property PhotoID As Nullable(Of Integer)
    Public Property PhotoDate As Nullable(Of Date)
    Public Property CardIssued As Boolean
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RowID As Byte()
    Public Property Relationship As Nullable(Of Short)
    Public Property Profession As Nullable(Of Short)
    Public Property Education As Nullable(Of Short)
    Public Property Email As String
    Public Property isOffline As Nullable(Of Boolean)
    Public Property TypeOfId As String
    Public Property HFID As Nullable(Of Integer)
    Public Property CurrentAddress As String
    Public Property GeoLocation As String
    Public Property CurrentVillage As Nullable(Of Integer)
    ''' new property
    
    Public Property IsHeadPhone1 As Boolean
    Public Property IsHeadPhone2 As Boolean
    Public Property DOB_unknow As Boolean
    Public Property AltPhone As String
    Public Property NetWorkProvider1 As String
    Public Property NetWorkProvider2 As String
    Public Property PreferredPaiementMode As String
    Public Property HeadStatus As String
    Public Property LengthPresentLocation As String
    Public Property MaleLivingHoushold As String
    Public Property FemaleLivingHoushold As String
    Public Property PersonLivingHoushold As String
    Public Property HHNBChildrenLivingM As String
    Public Property HHNBChildrenLivingF As String
    Public Property HHNBChildrenLivingT As String
    Public Property HHNBChildrenSchoolLivingM As String
    Public Property HHNBChildrenSchoolLivingF As String
    Public Property HHNBChildrenSchoolLivingT As String
    Public Property HHNBChildrenCompleteSchoolLivingM As String
    Public Property HHNBChildrenCompleteSchoolLivingF As String
    Public Property HHNBChildrenCompleteSchoolLivingT As String
    Public Property HHNBChildrenDropSchoolLivingM As String
    Public Property HHNBChildrenDropSchoolLivingF As String
    Public Property HHNBChildrenDropSchoolLivingT As String
    Public Property HHNBGirlsMarried As String
    Public Property HHNBChildrenBirthCertifM As String
    Public Property HHNBChildrenBirthCertifF As String
    Public Property HHNBChildrenBirthCertifT As String
    Public Property HHHealthStatus As String
    Public Property HHExpenditure As String
    Public Property HHExpenditurePerH As String
    Public Property HHNutritionalStatus As String
    Public Property HHMentalPhysicalDisability As String
    Public Property HHMentalPhysicalDisabilityM As String
    Public Property HHMentalPhysicalDisabilityF As String
    Public Property HHMentalPhysicalDisabilityT As String
    Public Property HHMentalPhysicalDisabilityO1 As Boolean
    Public Property HHMentalPhysicalDisabilityO2 As Boolean
    Public Property HHMentalPhysicalDisabilityO3 As Boolean
    Public Property HHMentalPhysicalDisabilityO4 As String
    Public Property ChildName As String
    Public Property ChildGender As String
    Public Property BirthDateChild As Date
    Public Property DateInconnueChild As Boolean
    Public Property CHBirthCertificate As String
    Public Property CHEnrolmentStatus As String
    Public Property ChildSchoolName As String
    Public Property CHEnrolmentWhichClass As String
    Public Property CHEnrolmentScore As String
    Public Property CHEnrolmentOutofSchool As String
    Public Property CHParentalStatus As String
    Public Property ResidentialStatus1 As Boolean
    Public Property ResidentialStatus2 As Boolean
    Public Property ResidentialStatus3 As Boolean
    Public Property ResidentialStatus4 As Boolean
    Public Property ResidentialStatus5 As Boolean
    Public Property ResidentialStatus6 As Boolean
    Public Property ResidentialStatus7 As Boolean
    Public Property CHSpecialNeeds1 As Boolean
    Public Property CHSpecialNeeds2 As Boolean
    Public Property CHSpecialNeeds3 As Boolean
    Public Property CHSpecialNeeds4 As Boolean
    Public Property CHSpecialNeeds5 As Boolean
    Public Property CHSpecialNeeds6 As String



    Public Overridable Property tblClaim As ICollection(Of tblClaim) = New HashSet(Of tblClaim)
    Public Overridable Property tblClaimDedRem As ICollection(Of tblClaimDedRem) = New HashSet(Of tblClaimDedRem)
    Public Overridable Property tblEducations As tblEducations
    Public Overridable Property tblFamilies As ICollection(Of tblFamilies) = New HashSet(Of tblFamilies)
    Public Overridable Property tblFamilies1 As tblFamilies
    Public Overridable Property tblHealthStatus As ICollection(Of tblHealthStatus) = New HashSet(Of tblHealthStatus)
    Public Overridable Property tblHF As tblHF
    Public Overridable Property tblIdentificationTypes As tblIdentificationTypes
    Public Overridable Property tblPhotos As tblPhotos
    Public Overridable Property tblInsureePolicy As ICollection(Of tblInsureePolicy) = New HashSet(Of tblInsureePolicy)
    Public Overridable Property tblPolicyRenewalDetails As ICollection(Of tblPolicyRenewalDetails) = New HashSet(Of tblPolicyRenewalDetails)
    Public Overridable Property tblPolicyRenewals As ICollection(Of tblPolicyRenewals) = New HashSet(Of tblPolicyRenewals)
    Public Overridable Property tblProfessions As tblProfessions
    Public Overridable Property tblRelations As tblRelations

End Class
